### ISSUE TITLE
operator-breakline up to here

### ISSUE THREAD

**Issue by blasco** [lambdalisue/vim-operator-breakline#2]
Would it be possible to provide a way to break the line up to the current cursor position instead of having to provide a number or changing the default setting?

**Comment by lambdalisue** [comment]
So do you mean something like '<Plug>(operator-breakline-right)' or whatever?

**Comment by blasco** [comment]
Yes exactly, something like that so this:
```
this is a <cursor>long line that will break at cursor position
```
becomes (approximately to) this:
```
this is a <cursor>
long line 
that will
break at 
cursor 
position
```

**Comment by lambdalisue** [comment]
Unfortunately, the cursor position seems lost in visual mode or operation pending mode so no way to get the correct position. I like the idea so if there is a way, let me know or send a PR.

Tested with

```vim
function! OperatorTest(motion_wiseness) abort
  echomsg string(getpos('.'))
  echomsg string(getcurpos())
  echomsg string(col('.'))
  echomsg string(getpos('`<'))
  echomsg string(getpos('`>'))
  echomsg string(getpos('`"'))
  echomsg string(getpos('`^'))
  echomsg string(getpos('`.'))
endfunction
call operator#user#define(
      \ 'breakline-test',
      \ 'OperatorTest')
nmap <C-g>t <Plug>(operator-breakline-test)
xmap <C-g>t <Plug>(operator-breakline-test)
```
